### ISSUE TITLE
Wrong output on par_put → par_delete → scan sequence

### ISSUE THREAD

**Issue by mavy** [CARV-ICS-FORTH/parallax#1]
The next sequence of calls produces wrong results (commit : 0ab2f77)

1. put ("/","16895|0|")
2. put ("Example", "Content")
3. par_delete("Example")
4. Scan ("",PAR_GREATER_OR_EQUAL);

Output : 

> Found element / -- [16895|0|]
> Found element Example -- [0|]

Without the remove, the output is the next one:

> Found element / -- [16895|0|]
> Found element Example -- [Content]

Trying to par_get the element "Example", after par_delete, returns a non exists code, which is correct.

Regards,

**Comment by innerout** [comment]
Hi Ramon, thanks for reporting the issue! I will look into it and report back in the coming days.

**Comment by innerout** [comment]
Ramon, I have fixed the bug in the 86a219fcddcd850895195821d393b8a061dc00ba commit. Can you check if you can still reproduce the bug?

**Comment by mavy** [comment]
Thanks, 
The bug is solved, the bug caused the close database operation to hang, but now works fine as well.
