### ISSUE TITLE
Ability to set log level

### ISSUE THREAD

**Issue by marcvef** [CARV-ICS-FORTH/parallax#2]
When using Parallax, we see a large amount of logging output (INFO and DEBUG) on stdout in both Debug and Release builds. I've seen that Parallax's used `log.h` header supports different log levels, but it seems to not be used by Parallax. 

Can this be added or is there another way to disable the logging output to stdout? Ideally, we would like to set a specific file where only Parallax logging is written to.

Thanks!

**Comment by innerout** [comment]
Hi Marc, thanks for opening this issue! We have added a CMake option to disable logging (-DDISABLE_LOGGING). In the future, we will also provide support to redirect output from `log_*` calls to a file.
