### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by hxhcreate** [CARV-ICS-FORTH/parallax#3]
Ubuntu18. 04 cmake version ==3.25  g++==7.5.0
error: non-trivial designated initializers not supported
pos: in YSCB-CXX/db/parallax_db.h    struct par_value lookup_value = { .val_buffer = NULL };

![image](https://user-images.githubusercontent.com/71424268/202749377-0b8f3304-9c2a-4a2b-b4f2-90b04673f519.png)

**Comment by innerout** [comment]
Hi @hxhcreate,  thanks for reporting this!
In our internal CI, we use gcc and g++ v10 to build Parallax on ubuntu focal.
For ubuntu 18.04, I found the following instructions to install gcc and g++ 10. Can you try installing from the link?https://askubuntu.com/questions/1192955/how-to-install-g-10-on-ubuntu-18-04
If v10 is installed successfully, you can use the following command to use the new compilers, and YCSB will probably build successfully.
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
```
Please tell us if this does not fix your problem, and we will investigate it further.

**Comment by hxhcreate** [comment]
Thanks! Solve this problem!
Have a good day

**Comment by hxhcreate** [comment]
Done
