### ISSUE TITLE
[refactor] cmake share libs flag

### ISSUE THREAD

**Issue by Toutou98** [CARV-ICS-FORTH/parallax#6]
I would like to request the addition of the -DBUILD_SHARED_LIBS=ON flag to the CMake configuration of this project.
From: cmake ..
To: cmake .. -DBUILD_SHARED_LIBS=ON

**Comment by innerout** [comment]
Hello @Toutou98, we already support this flag https://github.com/CARV-ICS-FORTH/parallax/blob/master/CMakeLists.txt#L12 .
